version: '3'
services:
  strapi:
    image: strapi/strapi
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: mongo # ${DATABASE_HOST} 
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./app:/srv/app
    # working_dir: /srv/app
    # command: bash -c "yarn dockeronstart" 
    # command: bash -c "npm i && npm run develop" 
    # Because different sharp version for mac && linux in docker
    ports:
      - '1337:1337'
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${DATABASE_ROOTPATH}data/${DATABASE_NAME}:/data/db

  adminconsole:
    build:
      context: ./adminconsole
    ports:
      - "3001:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./adminconsole:/usr/src/app/adminconsole
       - /usr/src/app/adminconsole/node_modules